dataset:
  value: "fluids.compressible.RiemannKelvinHelmholtz"
num_trajectories:
  value: 128
model_name:
  value: "S"
lr:
  value: 0.0005
weight_decay:
  value: 0.000001
lr_scheduler:
  value: "cosine"
warmup_ratio:
  value: 0.05
early_stopping_patience:
  value: 40
num_epochs:
  value: 400
batch_size:
  value: 40
max_grad_norm:
  value: 5.0
